<div class="zf-table-wrap">
    <div class="table-header">
        <input class="quick-search" value="<?php echo $this->quickSearch?>">
        <select class="itemPerPage">
            <?php foreach($this->itemCountPerPageValues as $item):?>
                <?php $selected = ($item == $this->itemCountPerPage) ? 'selected="selected"' : '""';?>
                <option <?php echo $selected?>><?php echo  $item?></option>
            <?php endforeach;?>
        </select>
    </div>
    <?php echo $this->table;?>
    <div class="table-footer">
        <div class="processing">
        </div>
        <?php echo $this->paginator;?>
    </div>
    <?php echo $this->paramsWrap;?>
</div>