<div class="zf-table-wrap  form-inline">
    <div class="table-header">
    </div>
    <div class="row ">
        <div class="col-sm-6 pull-left">
            <header>
                <h5><?= $this->name ?></h5>
            </header>
        </div>
        <?php if ($this->showQuickSearch): ?>
            <div class="dataTables_filter pull-right" id="dataTable_filter">
                <label>Search: <input type="text" aria-controls="dataTable" class="quick-search" value="<?php echo $this->quickSearch ?>">
                </label>
            </div>
        <?php endif; ?>
    </div>
    <?php echo $this->table; ?>
    <div class="row">
        <div class="col-sm-6 text-left">
            <?php if ($this->showItemPerPage): ?>
                <div class="dataTables_length">
                    <label class="pull-left">
                        <select class="itemPerPage form-control">
                            <?php foreach ($this->itemCountPerPageValues as $item): ?>
                                <?php $selected = ($item == $this->itemCountPerPage) ? 'selected="selected"' : '""'; ?>
                                <option <?php echo $selected ?>><?php echo $item ?></option>
                            <?php endforeach; ?>
                        </select> 
                    </label> 
                </div>
            <?php endif; ?>
        </div>
        <div class="col-sm-6 text-right">
            <?php if ($this->showPagination): ?>
                <div class="dataTables_paginate paging_bootstrap pagination">
                    <?php echo $this->paginator; ?>
                </div>
            <?php endif; ?>
        </div>
        <div class="processing">
        </div>
    </div>
    <?php echo $this->paramsWrap; ?>
</div>
