<div class="zf-table-wrap  form-inline">
    <div class="table-header">
        <div class="row-fluid ">
            <div class="pull-right dataTables_length">
                <label class="pull-right">
                 Show
                 <select class="itemPerPage">
                    <?php foreach($this->itemCountPerPageValues as $item):?>
                        <?php $selected = ($item == $this->itemCountPerPage) ? 'selected="selected"' : '""';?>
                        <option <?php echo $selected?>><?php echo  $item?></option>
                    <?php endforeach;?>
                </select> 
                </label> 
             </div>   
        </div>
        
    </div>
    <div class="content">
        <?php foreach($this->rows as $row):?>
        <div class="row-fluid" style="margin-bottom: 10px;">
            <div class="span2">
                <div class="logo">
                    <img src="/assets/img/elfinder/logo.png" width="50%"/>
                </div>
            </div>
            <div class="span8">
                Box /article title - Mr <?php echo $row['surname']?> <br />
                <?php echo $row['surname']?> <br />
                <?php echo $row['idcustomer']?> <br />
            </div>
            <div class="span2">
                City - <?php echo $row['city']?>
            </div>
        </div>
        <?php endforeach;?>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <div class="dataTables_filter" id="dataTable_filter">
                <label>Search: <input type="text" aria-controls="dataTable" class="quick-search" value="<?php echo $this->quickSearch?>">
                </label>
            </div>
        </div>
        <div class="span6">
            <div class="dataTables_paginate paging_bootstrap pagination">
                <?php echo $this->paginator; ?>
            </div>
        </div>
        <div class="processing">
        </div>
    </div>
    <?php echo $this->paramsWrap;?>
</div>

