<div class="params-wrap">
    <input type="hidden"  name="zfTablePage" value="<?php echo $this->page?>" />
    <input type="hidden"  name="zfTableColumn" value="<?php echo $this->column?>" />
    <input type="hidden"  name="zfTableOrder" value="<?php echo $this->order?>" />
    <input type="hidden"  name="zfTableQuickSearch" value="<?php echo $this->quickSearch?>" />
    <input type="hidden"  name="zfTableItemPerPage" value="<?php echo $this->itemCountPerPage?>" />
    <?if($this->rowAction):?>
        <a href="<?php echo $this->rowAction?>" class="rowAction"></a>
    <?endif;?>
</div>
