<div id="tableContainer"></div>
<hr />
<h4>Code/Information</h4>

<p>
    Advance ? Look below... In custom definition, only one thing we have to customize is template file ... 
    And in this example, we havent got a table, but pure html based on div and span. 
</p>
<pre>
$table->render('custom' , 'custom')
</pre>


<script>
    $("#tableContainer").zfTable('/table/ajax-advance');
</script>


