<div class="box">
    <header>
        <div class="icons"><i class="icon-move"></i></div>
        <h5>Dynamic Table</h5>
    </header>
    <div class="body">
        <div id="tableContainer">
                
        </div>
    </div>
</div>
<div class="box">
    <header>
        <div class="icons"><i class="icon-move"></i></div>
        <h5>Info</h5>
    </header>
    <div class="body">
        Advance ? Look below... In custom definition, only one thing we have to customize is template file ... 
        And in this example, we havent got a table, but pure html based on div and span. 
        <pre>
            $table->render('custom' , 'custom')
        </pre>
    </div>
</div>
<script>
    $("#tableContainer").zfTable('/table/ajax-advance');
</script>


