<div class="box">
    <header>
        <div class="icons"><i class="icon-move"></i></div>
        <h5>Dynamic Table</h5>
    </header>
    <div class="body">
        <div id="tableContainer">

        </div>
    </div>
</div>
<div class="box">
    <header>
        <div class="icons"><i class="icon-move"></i></div>
        <h5>Info</h5>
    </header>
    <div class="body">
       Base table without any decorations
    </div>
</div>
<script>
    $("#tableContainer").zfTable('/table/ajax-base');
</script>
