<ul class="intro">
    <li>
        Added support for Bootstrap 3.0.0.
    </li>
    <li>
        Added new filtering options - filtering by column
    </li>
    <li>
        Editable decorator -> the ability to edit data from the table level
    </li>
    <li>
       Row decorator for separeting row by ordering column (dividing the same data)
    </li>
    <li>
       Row decorator for variable attribute
    </li>
    <li>
       New conditions plugin : Between, GreaterThan, LesserThan
    </li>
    <li>
       Exporter to CSV
    </li>
    <li>
       The ability to configure from table level (additional possibility for module config)
    </li>
    <li>
        Attr and VarAttr Cell decorators for adding attributes to single Cell with possibility to add conditional decorating. 
    </li>
    <li>
       Deprecated initQuickSearchOption  - instead initFilters funtion
    </li>
</ul>