<div class="box">
    <header>
        <div class="icons"><i class="icon-move"></i></div>
        <h5>Dynamic Table</h5>
    </header>
    <div class="body">
           <?php
                echo $this->tableDataTable->render('dataTableAjaxInit');
            ?>
    </div>
</div>
<div class="box">
    <header>
        <div class="icons"><i class="icon-move"></i></div>
        <h5>Info</h5>
    </header>
    <div class="body">
       Rendered table looks very similar, but working on data table Engine. We render only html, and next call dataTable in javaScrrpt).
       <pre>
            echo $this->tableDataTable->render('dataTableAjaxInit');
            
            $(document).ready(function() {
                $('#zfDataTableExample').dataTable({
                    "sPaginationType": "bootstrap",
                    "sDom": "<'pull-right'l>t<'row-fluid'<'span6'f><'span6'p>>",
                    //"bProcessing": true,
                    "bServerSide": true,
                    //"iTotalRecords": 0,
                    "sServerMethod": "POST",
                    "sAjaxSource": '/table/ajax-data-table'
                });
            });
       </pre>
    </div>
</div>
 <script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('#zfDataTableExample').dataTable({
            "sPaginationType": "bootstrap",
            "sDom": "<'pull-right'l>t<'row-fluid'<'span6'f><'span6'p>>",
            //"bProcessing": true,
            "bServerSide": true,
            //"iTotalRecords": 0,
            "sServerMethod": "POST",
            "sAjaxSource": '/table/ajax-data-table'
        });
    });
</script>