<div id="tableContainer" class="zf-table-wrap">
     <?php
        echo $this->tableDataTable->render('dataTableAjaxInit');
     ?>
</div>

<hr />
<h4>Code/Information</h4>

<p>
    Base table without any decorations
</p>
<pre>


<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('#zfDataTableExample').dataTable({
            "sPaginationType": "bootstrap",
            "sDom": "<'pull-right'bl>t<'row'<'col-sm-6'f><'col-sm-6'p>>",
            "bServerSide": true,
            "sServerMethod": "POST",
            "sAjaxSource": '/table/ajax-data-table'
        });
    });
</script>


<!--<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('#zfDataTableExample').dataTable({
            "sPaginationType": "bootstrap",
            "sDom": "<'pull-right'l>t<'row-fluid'<'span6'f><'span6'p>>",
            "bServerSide": true,
            "sServerMethod": "POST",
            "sAjaxSource": '/table/ajax-data-table'
        });
    });
</script>-->