
<div id="tableContainer">
</div>

<script>
    $("#tableContainer").zfTable('/table/ajax-table');
    
</script>
 <script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('#example').dataTable({
					"bProcessing": true,
					"sAjaxSource": '/table/ajax-table2'
				});
    });
</script>

<table cellpadding="0" cellspacing="0" border="0" class="display" id="example" width="100%">
	<thead>
		<tr>
			<th>artist</th>
			<th>title</th>
		</tr>
	</thead>
	<tbody>
	</tbody>
	<tfoot>
		<tr>
			<th>artist</th>
			<th>title</th>
		</tr>
	</tfoot>
</table>

