
<div id="tableContainer">
</div>

<script>
    $("#tableContainer").zfTable('/table/ajax-base');
</script>

 <script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('#zfDataTableExample').dataTable({
            "bProcessing": true,
            "bServerSide": true,
            "sServerMethod": "POST",
            "sAjaxSource": '/table/ajax-data-table'
        });
    });
</script>

<?php
    echo $this->tableDataTable->render('dataTableAjaxInit');
?>
